// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiPostsByIdData, DeleteApiPostsByIdErrors, DeleteApiPostsByIdResponses, DeleteApiUsersByIdData, DeleteApiUsersByIdErrors, DeleteApiUsersByIdResponses, GetApiAuthMeData, GetApiAuthMeErrors, GetApiAuthMeResponses, GetApiPostsByIdData, GetApiPostsByIdErrors, GetApiPostsByIdResponses, GetApiPostsData, GetApiPostsErrors, GetApiPostsResponses, GetApiUsersByIdData, GetApiUsersByIdErrors, GetApiUsersByIdResponses, GetApiUsersData, GetApiUsersErrors, GetApiUsersResponses, GetData, GetResponses, PatchApiPostsByIdData, PatchApiPostsByIdErrors, PatchApiPostsByIdResponses, PatchApiUsersByIdData, PatchApiUsersByIdErrors, PatchApiUsersByIdResponses, PostApiAuthLoginData, PostApiAuthLoginErrors, PostApiAuthLoginResponses, PostApiAuthLogoutData, PostApiAuthLogoutResponses, PostApiAuthRefreshData, PostApiAuthRefreshErrors, PostApiAuthRefreshResponses, PostApiAuthRegisterData, PostApiAuthRegisterErrors, PostApiAuthRegisterResponses, PostApiPostsData, PostApiPostsErrors, PostApiPostsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

export const getApiAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiAuthMeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiAuthMeResponses, GetApiAuthMeErrors, ThrowOnError>({
        url: '/api/auth/me',
        ...options
    });
};

export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthLoginData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiAuthLoginResponses, PostApiAuthLoginErrors, ThrowOnError>({
        url: '/api/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const postApiAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthLogoutData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthLogoutResponses, unknown, ThrowOnError>({
        url: '/api/auth/logout',
        ...options
    });
};

export const postApiAuthRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthRefreshData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthRefreshResponses, PostApiAuthRefreshErrors, ThrowOnError>({
        url: '/api/auth/refresh',
        ...options
    });
};

export const postApiAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthRegisterData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiAuthRegisterResponses, PostApiAuthRegisterErrors, ThrowOnError>({
        url: '/api/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const deleteApiUsersById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiUsersByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteApiUsersByIdResponses, DeleteApiUsersByIdErrors, ThrowOnError>({
        url: '/api/users/{id}',
        ...options
    });
};

export const getApiUsersById = <ThrowOnError extends boolean = false>(options: Options<GetApiUsersByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiUsersByIdResponses, GetApiUsersByIdErrors, ThrowOnError>({
        url: '/api/users/{id}',
        ...options
    });
};

export const patchApiUsersById = <ThrowOnError extends boolean = false>(options: Options<PatchApiUsersByIdData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchApiUsersByIdResponses, PatchApiUsersByIdErrors, ThrowOnError>({
        url: '/api/users/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getApiUsers = <ThrowOnError extends boolean = false>(options?: Options<GetApiUsersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiUsersResponses, GetApiUsersErrors, ThrowOnError>({
        url: '/api/users/',
        ...options
    });
};

export const getApiPosts = <ThrowOnError extends boolean = false>(options?: Options<GetApiPostsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPostsResponses, GetApiPostsErrors, ThrowOnError>({
        url: '/api/posts/',
        ...options
    });
};

export const postApiPosts = <ThrowOnError extends boolean = false>(options: Options<PostApiPostsData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiPostsResponses, PostApiPostsErrors, ThrowOnError>({
        url: '/api/posts/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const deleteApiPostsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiPostsByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteApiPostsByIdResponses, DeleteApiPostsByIdErrors, ThrowOnError>({
        url: '/api/posts/{id}',
        ...options
    });
};

export const getApiPostsById = <ThrowOnError extends boolean = false>(options: Options<GetApiPostsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiPostsByIdResponses, GetApiPostsByIdErrors, ThrowOnError>({
        url: '/api/posts/{id}',
        ...options
    });
};

export const patchApiPostsById = <ThrowOnError extends boolean = false>(options: Options<PatchApiPostsByIdData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchApiPostsByIdResponses, PatchApiPostsByIdErrors, ThrowOnError>({
        url: '/api/posts/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
