// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteApiPostsById, deleteApiUsersById, get, getApiAuthMe, getApiPosts, getApiPostsById, getApiUsers, getApiUsersById, type Options, patchApiPostsById, patchApiUsersById, postApiAuthLogin, postApiAuthLogout, postApiAuthRefresh, postApiAuthRegister, postApiPosts } from '../sdk.gen';
import type { DeleteApiPostsByIdData, DeleteApiPostsByIdError, DeleteApiPostsByIdResponse, DeleteApiUsersByIdData, DeleteApiUsersByIdError, DeleteApiUsersByIdResponse, GetApiAuthMeData, GetApiPostsByIdData, GetApiPostsData, GetApiPostsError, GetApiPostsResponse, GetApiUsersByIdData, GetApiUsersData, GetApiUsersError, GetApiUsersResponse, GetData, PatchApiPostsByIdData, PatchApiPostsByIdError, PatchApiPostsByIdResponse, PatchApiUsersByIdData, PatchApiUsersByIdError, PatchApiUsersByIdResponse, PostApiAuthLoginData, PostApiAuthLoginError, PostApiAuthLoginResponse, PostApiAuthLogoutData, PostApiAuthLogoutResponse, PostApiAuthRefreshData, PostApiAuthRefreshError, PostApiAuthRefreshResponse, PostApiAuthRegisterData, PostApiAuthRegisterError, PostApiAuthRegisterResponse, PostApiPostsData, PostApiPostsError, PostApiPostsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getQueryKey = (options?: Options<GetData>) => createQueryKey('get', options);

export const getOptions = (options?: Options<GetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await get({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getQueryKey(options)
    });
};

export const getApiAuthMeQueryKey = (options?: Options<GetApiAuthMeData>) => createQueryKey('getApiAuthMe', options);

export const getApiAuthMeOptions = (options?: Options<GetApiAuthMeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiAuthMe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiAuthMeQueryKey(options)
    });
};

export const postApiAuthLoginMutation = (options?: Partial<Options<PostApiAuthLoginData>>): UseMutationOptions<PostApiAuthLoginResponse, PostApiAuthLoginError, Options<PostApiAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostApiAuthLoginResponse, PostApiAuthLoginError, Options<PostApiAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiAuthLogoutMutation = (options?: Partial<Options<PostApiAuthLogoutData>>): UseMutationOptions<PostApiAuthLogoutResponse, DefaultError, Options<PostApiAuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<PostApiAuthLogoutResponse, DefaultError, Options<PostApiAuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAuthLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiAuthRefreshMutation = (options?: Partial<Options<PostApiAuthRefreshData>>): UseMutationOptions<PostApiAuthRefreshResponse, PostApiAuthRefreshError, Options<PostApiAuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<PostApiAuthRefreshResponse, PostApiAuthRefreshError, Options<PostApiAuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAuthRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiAuthRegisterMutation = (options?: Partial<Options<PostApiAuthRegisterData>>): UseMutationOptions<PostApiAuthRegisterResponse, PostApiAuthRegisterError, Options<PostApiAuthRegisterData>> => {
    const mutationOptions: UseMutationOptions<PostApiAuthRegisterResponse, PostApiAuthRegisterError, Options<PostApiAuthRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAuthRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiUsersByIdMutation = (options?: Partial<Options<DeleteApiUsersByIdData>>): UseMutationOptions<DeleteApiUsersByIdResponse, DeleteApiUsersByIdError, Options<DeleteApiUsersByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteApiUsersByIdResponse, DeleteApiUsersByIdError, Options<DeleteApiUsersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiUsersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiUsersByIdQueryKey = (options: Options<GetApiUsersByIdData>) => createQueryKey('getApiUsersById', options);

export const getApiUsersByIdOptions = (options: Options<GetApiUsersByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiUsersById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiUsersByIdQueryKey(options)
    });
};

export const patchApiUsersByIdMutation = (options?: Partial<Options<PatchApiUsersByIdData>>): UseMutationOptions<PatchApiUsersByIdResponse, PatchApiUsersByIdError, Options<PatchApiUsersByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchApiUsersByIdResponse, PatchApiUsersByIdError, Options<PatchApiUsersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiUsersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiUsersQueryKey = (options?: Options<GetApiUsersData>) => createQueryKey('getApiUsers', options);

export const getApiUsersOptions = (options?: Options<GetApiUsersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiUsers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiUsersQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getApiUsersInfiniteQueryKey = (options?: Options<GetApiUsersData>): QueryKey<Options<GetApiUsersData>> => createQueryKey('getApiUsers', options, true);

export const getApiUsersInfiniteOptions = (options?: Options<GetApiUsersData>) => {
    return infiniteQueryOptions<GetApiUsersResponse, GetApiUsersError, InfiniteData<GetApiUsersResponse>, QueryKey<Options<GetApiUsersData>>, number | Pick<QueryKey<Options<GetApiUsersData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetApiUsersData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getApiUsers({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiUsersInfiniteQueryKey(options)
    });
};

export const getApiPostsQueryKey = (options?: Options<GetApiPostsData>) => createQueryKey('getApiPosts', options);

export const getApiPostsOptions = (options?: Options<GetApiPostsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiPosts({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiPostsQueryKey(options)
    });
};

export const getApiPostsInfiniteQueryKey = (options?: Options<GetApiPostsData>): QueryKey<Options<GetApiPostsData>> => createQueryKey('getApiPosts', options, true);

export const getApiPostsInfiniteOptions = (options?: Options<GetApiPostsData>) => {
    return infiniteQueryOptions<GetApiPostsResponse, GetApiPostsError, InfiniteData<GetApiPostsResponse>, QueryKey<Options<GetApiPostsData>>, number | Pick<QueryKey<Options<GetApiPostsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetApiPostsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getApiPosts({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiPostsInfiniteQueryKey(options)
    });
};

export const postApiPostsMutation = (options?: Partial<Options<PostApiPostsData>>): UseMutationOptions<PostApiPostsResponse, PostApiPostsError, Options<PostApiPostsData>> => {
    const mutationOptions: UseMutationOptions<PostApiPostsResponse, PostApiPostsError, Options<PostApiPostsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiPosts({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiPostsByIdMutation = (options?: Partial<Options<DeleteApiPostsByIdData>>): UseMutationOptions<DeleteApiPostsByIdResponse, DeleteApiPostsByIdError, Options<DeleteApiPostsByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteApiPostsByIdResponse, DeleteApiPostsByIdError, Options<DeleteApiPostsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiPostsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiPostsByIdQueryKey = (options: Options<GetApiPostsByIdData>) => createQueryKey('getApiPostsById', options);

export const getApiPostsByIdOptions = (options: Options<GetApiPostsByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiPostsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiPostsByIdQueryKey(options)
    });
};

export const patchApiPostsByIdMutation = (options?: Partial<Options<PatchApiPostsByIdData>>): UseMutationOptions<PatchApiPostsByIdResponse, PatchApiPostsByIdError, Options<PatchApiPostsByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchApiPostsByIdResponse, PatchApiPostsByIdError, Options<PatchApiPostsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiPostsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
